In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [40]:
V = np.zeros(5)
V_prev = V
print(V)
err = 0.01

while (True):
    tri = 0
    print(V)
    print(V_prev)
    V_prev = V
    for i in range(1,4):
        v = V[i]
        v_temp = 0.5*(-1+V[i-1])+0.5*(-1+V[i+1])
        print(v_temp)
        print(abs(v-v_temp))
        tri = max(tri, abs(v-v_temp))
        V_prev[i] = v_temp
    V = V_prev
    if err > tri:
        break;
        
print(V)

[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
-1.0
1.0
-1.5
1.5
-1.75
1.75
[ 0.   -1.   -1.5  -1.75  0.  ]
[ 0.   -1.   -1.5  -1.75  0.  ]
-1.75
0.75
-2.75
1.25
-2.375
0.625
[ 0.    -1.75  -2.75  -2.375  0.   ]
[ 0.    -1.75  -2.75  -2.375  0.   ]
-2.375
0.625
-3.375
0.625
-2.6875
0.3125
[ 0.     -2.375  -3.375  -2.6875  0.    ]
[ 0.     -2.375  -3.375  -2.6875  0.    ]
-2.6875
0.3125
-3.6875
0.3125
-2.84375
0.15625
[ 0.      -2.6875  -3.6875  -2.84375  0.     ]
[ 0.      -2.6875  -3.6875  -2.84375  0.     ]
-2.84375
0.15625
-3.84375
0.15625
-2.921875
0.078125
[ 0.       -2.84375  -3.84375  -2.921875  0.      ]
[ 0.       -2.84375  -3.84375  -2.921875  0.      ]
-2.921875
0.078125
-3.921875
0.078125
-2.9609375
0.0390625
[ 0.        -2.921875  -3.921875  -2.9609375  0.       ]
[ 0.        -2.921875  -3.921875  -2.9609375  0.       ]
-2.9609375
0.0390625
-3.9609375
0.0390625
-2.98046875
0.01953125
[ 0.         -2.9609375  -3.9609375  -2.98046875  0.        ]
[ 0.         -2.9609375 